## Catalog update view error

```py
 File "/home/wallace/.local/lib/python3.8/site-packages/django/views/generic/edit.py", line 116, in get_success_url
    url = self.object.get_absolute_url()
AttributeError: 'Catalog' object has no attribute 'get_absolute_url'
```